//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace LitePlacer.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("COM3")]
        public string CNC_SerialPort {
            get {
                return ((string)(this["CNC_SerialPort"]));
            }
            set {
                this["CNC_SerialPort"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.1")]
        public double DownCam_XmmPerPixel {
            get {
                return ((double)(this["DownCam_XmmPerPixel"]));
            }
            set {
                this["DownCam_XmmPerPixel"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.1")]
        public double DownCam_YmmPerPixel {
            get {
                return ((double)(this["DownCam_YmmPerPixel"]));
            }
            set {
                this["DownCam_YmmPerPixel"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string TinyG_sys {
            get {
                return ((string)(this["TinyG_sys"]));
            }
            set {
                this["TinyG_sys"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string TinyG_x {
            get {
                return ((string)(this["TinyG_x"]));
            }
            set {
                this["TinyG_x"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string TinyG_y {
            get {
                return ((string)(this["TinyG_y"]));
            }
            set {
                this["TinyG_y"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string TinyG_z {
            get {
                return ((string)(this["TinyG_z"]));
            }
            set {
                this["TinyG_z"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string TinyG_a {
            get {
                return ((string)(this["TinyG_a"]));
            }
            set {
                this["TinyG_a"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string TinyG_m1 {
            get {
                return ((string)(this["TinyG_m1"]));
            }
            set {
                this["TinyG_m1"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string TinyG_m2 {
            get {
                return ((string)(this["TinyG_m2"]));
            }
            set {
                this["TinyG_m2"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string TinyG_m3 {
            get {
                return ((string)(this["TinyG_m3"]));
            }
            set {
                this["TinyG_m3"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string TinyG_m4 {
            get {
                return ((string)(this["TinyG_m4"]));
            }
            set {
                this["TinyG_m4"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool TinyG_settings_saved {
            get {
                return ((bool)(this["TinyG_settings_saved"]));
            }
            set {
                this["TinyG_settings_saved"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public int DownCam_index {
            get {
                return ((int)(this["DownCam_index"]));
            }
            set {
                this["DownCam_index"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public double General_JigOffsetX {
            get {
                return ((double)(this["General_JigOffsetX"]));
            }
            set {
                this["General_JigOffsetX"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public double General_JigOffsetY {
            get {
                return ((double)(this["General_JigOffsetY"]));
            }
            set {
                this["General_JigOffsetY"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_ParkX {
            get {
                return ((double)(this["General_ParkX"]));
            }
            set {
                this["General_ParkX"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_ParkY {
            get {
                return ((double)(this["General_ParkY"]));
            }
            set {
                this["General_ParkY"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("50000")]
        public string General_MediumSpeed {
            get {
                return ((string)(this["General_MediumSpeed"]));
            }
            set {
                this["General_MediumSpeed"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1.5")]
        public double DownCam_Zoomfactor {
            get {
                return ((double)(this["DownCam_Zoomfactor"]));
            }
            set {
                this["DownCam_Zoomfactor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool DownCam_Zoom {
            get {
                return ((bool)(this["DownCam_Zoom"]));
            }
            set {
                this["DownCam_Zoom"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_PickupCenterX {
            get {
                return ((double)(this["General_PickupCenterX"]));
            }
            set {
                this["General_PickupCenterX"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_PickupCenterY {
            get {
                return ((double)(this["General_PickupCenterY"]));
            }
            set {
                this["General_PickupCenterY"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("-1")]
        public int UpCam_index {
            get {
                return ((int)(this["UpCam_index"]));
            }
            set {
                this["UpCam_index"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.05")]
        public double UpCam_XmmPerPixel {
            get {
                return ((double)(this["UpCam_XmmPerPixel"]));
            }
            set {
                this["UpCam_XmmPerPixel"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.05")]
        public double UpCam_YmmPerPixel {
            get {
                return ((double)(this["UpCam_YmmPerPixel"]));
            }
            set {
                this["UpCam_YmmPerPixel"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool UpCam_Zoom {
            get {
                return ((bool)(this["UpCam_Zoom"]));
            }
            set {
                this["UpCam_Zoom"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1.5")]
        public double UpCam_Zoomfactor {
            get {
                return ((double)(this["UpCam_Zoomfactor"]));
            }
            set {
                this["UpCam_Zoomfactor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2")]
        public double UpCam_PositionX {
            get {
                return ((double)(this["UpCam_PositionX"]));
            }
            set {
                this["UpCam_PositionX"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("3")]
        public double UpCam_PositionY {
            get {
                return ((double)(this["UpCam_PositionY"]));
            }
            set {
                this["UpCam_PositionY"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("75")]
        public double DownCam_NeedleOffsetX {
            get {
                return ((double)(this["DownCam_NeedleOffsetX"]));
            }
            set {
                this["DownCam_NeedleOffsetX"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("29")]
        public double DownCam_NeedleOffsetY {
            get {
                return ((double)(this["DownCam_NeedleOffsetY"]));
            }
            set {
                this["DownCam_NeedleOffsetY"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("590")]
        public double General_MachineSizeX {
            get {
                return ((double)(this["General_MachineSizeX"]));
            }
            set {
                this["General_MachineSizeX"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("370")]
        public double General_MachineSizeY {
            get {
                return ((double)(this["General_MachineSizeY"]));
            }
            set {
                this["General_MachineSizeY"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.2")]
        public double General_ProbingBackOff {
            get {
                return ((double)(this["General_ProbingBackOff"]));
            }
            set {
                this["General_ProbingBackOff"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_ZtoPCB {
            get {
                return ((double)(this["General_ZtoPCB"]));
            }
            set {
                this["General_ZtoPCB"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1000")]
        public int CNC_ZspeedMax {
            get {
                return ((int)(this["CNC_ZspeedMax"]));
            }
            set {
                this["CNC_ZspeedMax"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1000")]
        public int CNC_AspeedMax {
            get {
                return ((int)(this["CNC_AspeedMax"]));
            }
            set {
                this["CNC_AspeedMax"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("250")]
        public int General_PickupVacuumTime {
            get {
                return ((int)(this["General_PickupVacuumTime"]));
            }
            set {
                this["General_PickupVacuumTime"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("150")]
        public int General_PickupReleaseTime {
            get {
                return ((int)(this["General_PickupReleaseTime"]));
            }
            set {
                this["General_PickupReleaseTime"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("100")]
        public int DownCam_MeasurementDelay {
            get {
                return ((int)(this["DownCam_MeasurementDelay"]));
            }
            set {
                this["DownCam_MeasurementDelay"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("100")]
        public int UpCam_MeasurementDelay {
            get {
                return ((int)(this["UpCam_MeasurementDelay"]));
            }
            set {
                this["UpCam_MeasurementDelay"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool CNC_SlackCompensation {
            get {
                return ((bool)(this["CNC_SlackCompensation"]));
            }
            set {
                this["CNC_SlackCompensation"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_Mark1X {
            get {
                return ((double)(this["General_Mark1X"]));
            }
            set {
                this["General_Mark1X"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_Mark1Y {
            get {
                return ((double)(this["General_Mark1Y"]));
            }
            set {
                this["General_Mark1Y"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Mark1")]
        public string General_Mark1Name {
            get {
                return ((string)(this["General_Mark1Name"]));
            }
            set {
                this["General_Mark1Name"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_Mark2X {
            get {
                return ((double)(this["General_Mark2X"]));
            }
            set {
                this["General_Mark2X"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_Mark2Y {
            get {
                return ((double)(this["General_Mark2Y"]));
            }
            set {
                this["General_Mark2Y"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Mark2")]
        public string General_Mark2Name {
            get {
                return ((string)(this["General_Mark2Name"]));
            }
            set {
                this["General_Mark2Name"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_Mark3X {
            get {
                return ((double)(this["General_Mark3X"]));
            }
            set {
                this["General_Mark3X"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_Mark3Y {
            get {
                return ((double)(this["General_Mark3Y"]));
            }
            set {
                this["General_Mark3Y"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Mark3")]
        public string General_Mark3Name {
            get {
                return ((string)(this["General_Mark3Name"]));
            }
            set {
                this["General_Mark3Name"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_Mark4X {
            get {
                return ((double)(this["General_Mark4X"]));
            }
            set {
                this["General_Mark4X"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_Mark4Y {
            get {
                return ((double)(this["General_Mark4Y"]));
            }
            set {
                this["General_Mark4Y"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Mark4")]
        public string General_Mark4Name {
            get {
                return ((string)(this["General_Mark4Name"]));
            }
            set {
                this["General_Mark4Name"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_Mark5X {
            get {
                return ((double)(this["General_Mark5X"]));
            }
            set {
                this["General_Mark5X"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_Mark5Y {
            get {
                return ((double)(this["General_Mark5Y"]));
            }
            set {
                this["General_Mark5Y"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Mark5")]
        public string General_Mark5Name {
            get {
                return ((string)(this["General_Mark5Name"]));
            }
            set {
                this["General_Mark5Name"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_Mark6X {
            get {
                return ((double)(this["General_Mark6X"]));
            }
            set {
                this["General_Mark6X"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double General_Mark6Y {
            get {
                return ((double)(this["General_Mark6Y"]));
            }
            set {
                this["General_Mark6Y"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Mark6")]
        public string General_Mark6Name {
            get {
                return ((string)(this["General_Mark6Name"]));
            }
            set {
                this["General_Mark6Name"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool Downcam_InvertedHomeMark {
            get {
                return ((bool)(this["Downcam_InvertedHomeMark"]));
            }
            set {
                this["Downcam_InvertedHomeMark"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("150")]
        public decimal CNC_SmallMovementSpeed {
            get {
                return ((decimal)(this["CNC_SmallMovementSpeed"]));
            }
            set {
                this["CNC_SmallMovementSpeed"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool Placement_UpdateJobGridAtRuntime {
            get {
                return ((bool)(this["Placement_UpdateJobGridAtRuntime"]));
            }
            set {
                this["Placement_UpdateJobGridAtRuntime"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DownCam_DrawTicks {
            get {
                return ((bool)(this["DownCam_DrawTicks"]));
            }
            set {
                this["DownCam_DrawTicks"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double CNC_SquareCorrection {
            get {
                return ((double)(this["CNC_SquareCorrection"]));
            }
            set {
                this["CNC_SquareCorrection"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("20")]
        public double General_ZTestTravel {
            get {
                return ((double)(this["General_ZTestTravel"]));
            }
            set {
                this["General_ZTestTravel"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool General_UpgradeRequired {
            get {
                return ((bool)(this["General_UpgradeRequired"]));
            }
            set {
                this["General_UpgradeRequired"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string template_file {
            get {
                return ((string)(this["template_file"]));
            }
            set {
                this["template_file"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool use_template {
            get {
                return ((bool)(this["use_template"]));
            }
            set {
                this["use_template"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.7")]
        public double template_threshold {
            get {
                return ((double)(this["template_threshold"]));
            }
            set {
                this["template_threshold"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("^FID?")]
        public string fiducial_designator_regexp {
            get {
                return ((string)(this["fiducial_designator_regexp"]));
            }
            set {
                this["fiducial_designator_regexp"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double z_offset {
            get {
                return ((double)(this["z_offset"]));
            }
            set {
                this["z_offset"] = value;
            }
        }
    }
}
