//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitePlacer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string CNC_SerialPort {
            get {
                return ((string)(this["CNC_SerialPort"]));
            }
            set {
                this["CNC_SerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double DownCam_XmmPerPixel {
            get {
                return ((double)(this["DownCam_XmmPerPixel"]));
            }
            set {
                this["DownCam_XmmPerPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double DownCam_YmmPerPixel {
            get {
                return ((double)(this["DownCam_YmmPerPixel"]));
            }
            set {
                this["DownCam_YmmPerPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TinyG_sys {
            get {
                return ((string)(this["TinyG_sys"]));
            }
            set {
                this["TinyG_sys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TinyG_x {
            get {
                return ((string)(this["TinyG_x"]));
            }
            set {
                this["TinyG_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TinyG_y {
            get {
                return ((string)(this["TinyG_y"]));
            }
            set {
                this["TinyG_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TinyG_z {
            get {
                return ((string)(this["TinyG_z"]));
            }
            set {
                this["TinyG_z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TinyG_a {
            get {
                return ((string)(this["TinyG_a"]));
            }
            set {
                this["TinyG_a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TinyG_m1 {
            get {
                return ((string)(this["TinyG_m1"]));
            }
            set {
                this["TinyG_m1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TinyG_m2 {
            get {
                return ((string)(this["TinyG_m2"]));
            }
            set {
                this["TinyG_m2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TinyG_m3 {
            get {
                return ((string)(this["TinyG_m3"]));
            }
            set {
                this["TinyG_m3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TinyG_m4 {
            get {
                return ((string)(this["TinyG_m4"]));
            }
            set {
                this["TinyG_m4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TinyG_settings_saved {
            get {
                return ((bool)(this["TinyG_settings_saved"]));
            }
            set {
                this["TinyG_settings_saved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DownCam_index {
            get {
                return ((int)(this["DownCam_index"]));
            }
            set {
                this["DownCam_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double General_JigOffsetX {
            get {
                return ((double)(this["General_JigOffsetX"]));
            }
            set {
                this["General_JigOffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double General_JigOffsetY {
            get {
                return ((double)(this["General_JigOffsetY"]));
            }
            set {
                this["General_JigOffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_ParkX {
            get {
                return ((double)(this["General_ParkX"]));
            }
            set {
                this["General_ParkX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_ParkY {
            get {
                return ((double)(this["General_ParkY"]));
            }
            set {
                this["General_ParkY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public string General_MediumSpeed {
            get {
                return ((string)(this["General_MediumSpeed"]));
            }
            set {
                this["General_MediumSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double DownCam_Zoomfactor {
            get {
                return ((double)(this["DownCam_Zoomfactor"]));
            }
            set {
                this["DownCam_Zoomfactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DownCam_Zoom {
            get {
                return ((bool)(this["DownCam_Zoom"]));
            }
            set {
                this["DownCam_Zoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_PickupCenterX {
            get {
                return ((double)(this["General_PickupCenterX"]));
            }
            set {
                this["General_PickupCenterX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_PickupCenterY {
            get {
                return ((double)(this["General_PickupCenterY"]));
            }
            set {
                this["General_PickupCenterY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int UpCam_index {
            get {
                return ((int)(this["UpCam_index"]));
            }
            set {
                this["UpCam_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public double UpCam_XmmPerPixel {
            get {
                return ((double)(this["UpCam_XmmPerPixel"]));
            }
            set {
                this["UpCam_XmmPerPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public double UpCam_YmmPerPixel {
            get {
                return ((double)(this["UpCam_YmmPerPixel"]));
            }
            set {
                this["UpCam_YmmPerPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpCam_Zoom {
            get {
                return ((bool)(this["UpCam_Zoom"]));
            }
            set {
                this["UpCam_Zoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double UpCam_Zoomfactor {
            get {
                return ((double)(this["UpCam_Zoomfactor"]));
            }
            set {
                this["UpCam_Zoomfactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double UpCam_PositionX {
            get {
                return ((double)(this["UpCam_PositionX"]));
            }
            set {
                this["UpCam_PositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double UpCam_PositionY {
            get {
                return ((double)(this["UpCam_PositionY"]));
            }
            set {
                this["UpCam_PositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public double DownCam_NeedleOffsetX {
            get {
                return ((double)(this["DownCam_NeedleOffsetX"]));
            }
            set {
                this["DownCam_NeedleOffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29")]
        public double DownCam_NeedleOffsetY {
            get {
                return ((double)(this["DownCam_NeedleOffsetY"]));
            }
            set {
                this["DownCam_NeedleOffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("590")]
        public double General_MachineSizeX {
            get {
                return ((double)(this["General_MachineSizeX"]));
            }
            set {
                this["General_MachineSizeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("370")]
        public double General_MachineSizeY {
            get {
                return ((double)(this["General_MachineSizeY"]));
            }
            set {
                this["General_MachineSizeY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double General_ProbingBackOff {
            get {
                return ((double)(this["General_ProbingBackOff"]));
            }
            set {
                this["General_ProbingBackOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_ZtoPCB {
            get {
                return ((double)(this["General_ZtoPCB"]));
            }
            set {
                this["General_ZtoPCB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int CNC_ZspeedMax {
            get {
                return ((int)(this["CNC_ZspeedMax"]));
            }
            set {
                this["CNC_ZspeedMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int CNC_AspeedMax {
            get {
                return ((int)(this["CNC_AspeedMax"]));
            }
            set {
                this["CNC_AspeedMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int General_PickupVacuumTime {
            get {
                return ((int)(this["General_PickupVacuumTime"]));
            }
            set {
                this["General_PickupVacuumTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int General_PickupReleaseTime {
            get {
                return ((int)(this["General_PickupReleaseTime"]));
            }
            set {
                this["General_PickupReleaseTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DownCam_MeasurementDelay {
            get {
                return ((int)(this["DownCam_MeasurementDelay"]));
            }
            set {
                this["DownCam_MeasurementDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int UpCam_MeasurementDelay {
            get {
                return ((int)(this["UpCam_MeasurementDelay"]));
            }
            set {
                this["UpCam_MeasurementDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CNC_SlackCompensation {
            get {
                return ((bool)(this["CNC_SlackCompensation"]));
            }
            set {
                this["CNC_SlackCompensation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_Mark1X {
            get {
                return ((double)(this["General_Mark1X"]));
            }
            set {
                this["General_Mark1X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_Mark1Y {
            get {
                return ((double)(this["General_Mark1Y"]));
            }
            set {
                this["General_Mark1Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mark1")]
        public string General_Mark1Name {
            get {
                return ((string)(this["General_Mark1Name"]));
            }
            set {
                this["General_Mark1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_Mark2X {
            get {
                return ((double)(this["General_Mark2X"]));
            }
            set {
                this["General_Mark2X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_Mark2Y {
            get {
                return ((double)(this["General_Mark2Y"]));
            }
            set {
                this["General_Mark2Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mark2")]
        public string General_Mark2Name {
            get {
                return ((string)(this["General_Mark2Name"]));
            }
            set {
                this["General_Mark2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_Mark3X {
            get {
                return ((double)(this["General_Mark3X"]));
            }
            set {
                this["General_Mark3X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_Mark3Y {
            get {
                return ((double)(this["General_Mark3Y"]));
            }
            set {
                this["General_Mark3Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mark3")]
        public string General_Mark3Name {
            get {
                return ((string)(this["General_Mark3Name"]));
            }
            set {
                this["General_Mark3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_Mark4X {
            get {
                return ((double)(this["General_Mark4X"]));
            }
            set {
                this["General_Mark4X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_Mark4Y {
            get {
                return ((double)(this["General_Mark4Y"]));
            }
            set {
                this["General_Mark4Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mark4")]
        public string General_Mark4Name {
            get {
                return ((string)(this["General_Mark4Name"]));
            }
            set {
                this["General_Mark4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_Mark5X {
            get {
                return ((double)(this["General_Mark5X"]));
            }
            set {
                this["General_Mark5X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_Mark5Y {
            get {
                return ((double)(this["General_Mark5Y"]));
            }
            set {
                this["General_Mark5Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mark5")]
        public string General_Mark5Name {
            get {
                return ((string)(this["General_Mark5Name"]));
            }
            set {
                this["General_Mark5Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_Mark6X {
            get {
                return ((double)(this["General_Mark6X"]));
            }
            set {
                this["General_Mark6X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_Mark6Y {
            get {
                return ((double)(this["General_Mark6Y"]));
            }
            set {
                this["General_Mark6Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mark6")]
        public string General_Mark6Name {
            get {
                return ((string)(this["General_Mark6Name"]));
            }
            set {
                this["General_Mark6Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Downcam_InvertedHomeMark {
            get {
                return ((bool)(this["Downcam_InvertedHomeMark"]));
            }
            set {
                this["Downcam_InvertedHomeMark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public decimal CNC_SmallMovementSpeed {
            get {
                return ((decimal)(this["CNC_SmallMovementSpeed"]));
            }
            set {
                this["CNC_SmallMovementSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Placement_UpdateJobGridAtRuntime {
            get {
                return ((bool)(this["Placement_UpdateJobGridAtRuntime"]));
            }
            set {
                this["Placement_UpdateJobGridAtRuntime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DownCam_DrawTicks {
            get {
                return ((bool)(this["DownCam_DrawTicks"]));
            }
            set {
                this["DownCam_DrawTicks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CNC_SquareCorrection {
            get {
                return ((double)(this["CNC_SquareCorrection"]));
            }
            set {
                this["CNC_SquareCorrection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double General_ZTestTravel {
            get {
                return ((double)(this["General_ZTestTravel"]));
            }
            set {
                this["General_ZTestTravel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_UpgradeRequired {
            get {
                return ((bool)(this["General_UpgradeRequired"]));
            }
            set {
                this["General_UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double General_ShadeGuard_mm {
            get {
                return ((double)(this["General_ShadeGuard_mm"]));
            }
            set {
                this["General_ShadeGuard_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Panel_XFirstOffset {
            get {
                return ((double)(this["Panel_XFirstOffset"]));
            }
            set {
                this["Panel_XFirstOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Panel_YFirstOffset {
            get {
                return ((double)(this["Panel_YFirstOffset"]));
            }
            set {
                this["Panel_YFirstOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Panel_XRepeats {
            get {
                return ((int)(this["Panel_XRepeats"]));
            }
            set {
                this["Panel_XRepeats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Panel_YRepeats {
            get {
                return ((int)(this["Panel_YRepeats"]));
            }
            set {
                this["Panel_YRepeats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Panel_XIncrement {
            get {
                return ((double)(this["Panel_XIncrement"]));
            }
            set {
                this["Panel_XIncrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Panel_YIncrement {
            get {
                return ((double)(this["Panel_YIncrement"]));
            }
            set {
                this["Panel_YIncrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Panel_UseBoardFids {
            get {
                return ((bool)(this["Panel_UseBoardFids"]));
            }
            set {
                this["Panel_UseBoardFids"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cameras_RobustSwitch {
            get {
                return ((bool)(this["Cameras_RobustSwitch"]));
            }
            set {
                this["Cameras_RobustSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color DownCam_SnapshotColor {
            get {
                return ((global::System.Drawing.Color)(this["DownCam_SnapshotColor"]));
            }
            set {
                this["DownCam_SnapshotColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color UpCam_SnapshotColor {
            get {
                return ((global::System.Drawing.Color)(this["UpCam_SnapshotColor"]));
            }
            set {
                this["UpCam_SnapshotColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int CNC_CtlrJogSpeed {
            get {
                return ((int)(this["CNC_CtlrJogSpeed"]));
            }
            set {
                this["CNC_CtlrJogSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int CNC_NormalJogSpeed {
            get {
                return ((int)(this["CNC_NormalJogSpeed"]));
            }
            set {
                this["CNC_NormalJogSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public int CNC_AltJogSpeed {
            get {
                return ((int)(this["CNC_AltJogSpeed"]));
            }
            set {
                this["CNC_AltJogSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CNC_SlackCompensationA {
            get {
                return ((bool)(this["CNC_SlackCompensationA"]));
            }
            set {
                this["CNC_SlackCompensationA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Placement_Depth {
            get {
                return ((double)(this["Placement_Depth"]));
            }
            set {
                this["Placement_Depth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Placement_OmitNeedleCalibration {
            get {
                return ((bool)(this["Placement_OmitNeedleCalibration"]));
            }
            set {
                this["Placement_OmitNeedleCalibration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Placement_SkipMeasurements {
            get {
                return ((bool)(this["Placement_SkipMeasurements"]));
            }
            set {
                this["Placement_SkipMeasurements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cameras_KeepActive {
            get {
                return ((bool)(this["Cameras_KeepActive"]));
            }
            set {
                this["Cameras_KeepActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CNC_EnableNumPadJog {
            get {
                return ((bool)(this["CNC_EnableNumPadJog"]));
            }
            set {
                this["CNC_EnableNumPadJog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CNC_EnableMouseWheelJog {
            get {
                return ((bool)(this["CNC_EnableMouseWheelJog"]));
            }
            set {
                this["CNC_EnableMouseWheelJog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_CheckForUpdates {
            get {
                return ((bool)(this["General_CheckForUpdates"]));
            }
            set {
                this["General_CheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_MuteLogging {
            get {
                return ((bool)(this["General_MuteLogging"]));
            }
            set {
                this["General_MuteLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UpcamMoniker {
            get {
                return ((string)(this["UpcamMoniker"]));
            }
            set {
                this["UpcamMoniker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DowncamMoniker {
            get {
                return ((string)(this["DowncamMoniker"]));
            }
            set {
                this["DowncamMoniker"] = value;
            }
        }
    }
}
